# Generated by Django 5.1.6 on 2025-12-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emapp", "0007_results_image_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_1_2_text", models.CharField(default="NAN", max_length=100)),
                ("set_3_4_text", models.CharField(default="NAN", max_length=100)),
            ],
        ),
    ]
